News
geekhub-php/theatre-front pull request #174
Opened 2021-04-06 12:56 UTC by NataliyaKoval

2021-04-08 06:26 UTC, yana-tsylinska commented on src/app/components/article/article.component.html
> +  <h1>Новина</h1>
по дефотлту в темплейтах має бути англійський текст і доданий `i18n` атрибут для перекладу

2021-04-08 06:26 UTC, yana-tsylinska commented on src/app/components/article/article.component.html
> +<!--<div class="container">-->
закоментований код може залишатись в репозиторії тільки якщо в найближчому майбутньому він буде знову використовуватись, але все одно це треба додатково пояснювати
якщо це не цей випадок - нещадно видаляєм, це зайвий 'мусор'))

2021-04-08 06:26 UTC, yana-tsylinska commented on src/app/components/article/article.component.html
> +      <div class="date">{{ item.created_at | date: 'd.MM.yyyy' }}</div>
тут можна `p`-елемент використати))

2021-04-08 06:26 UTC, yana-tsylinska commented on src/app/components/news/news.component.html
> +    <div>
для чого тобі тут додатковий `div`-врапер?

2021-04-08 06:26 UTC, yana-tsylinska commented on src/app/components/partials/news-list-item/news-list-item.component.html
> +  <div class="news-item">
ось цю `div`-ку можна змерджити з лінкою, просто перенеси клис на `a` і ти знову ж таки позбувається ще одного зайвого врапера)))

2021-04-08 06:26 UTC, yana-tsylinska commented on src/app/components/news/news.component.scss
> +  font-family: KobzarKS;
для шрифту і кольорів мають бути глобальні змінні (здається Таня працює над цим) - як тільки той таск/пр буде завершений і вмерджений в девелоп, тобі потрібно буде просінкатись з девелопом і проапдейтити свої стилі)

2021-04-08 07:33 UTC, NataliyaKoval commented on src/app/components/article/article.component.html
> +  <h1>Новина</h1>
done

2021-04-08 07:34 UTC, NataliyaKoval commented on src/app/components/article/article.component.html
> +<!--<div class="container">-->
done

2021-04-08 07:34 UTC, NataliyaKoval commented on src/app/components/article/article.component.html
> +      <div class="date">{{ item.created_at | date: 'd.MM.yyyy' }}</div>
done

2021-04-08 07:35 UTC, NataliyaKoval commented on src/app/components/news/news.component.html
> +    <div>
deleted

2021-04-08 07:36 UTC, NataliyaKoval commented on src/app/components/partials/news-list-item/news-list-item.component.html
> +  <div class="news-item">
done

2021-04-21 16:09 UTC, Serhio77777 commented on src/app/store/news/NewsItemImage.ts
>    post_big: Image;
Why underscore?

2021-04-23 14:15 UTC, NataliyaKoval commented on src/app/store/news/NewsItemImage.ts
>    post_big: Image;
It's a name received from backend.

2021-04-26 09:08 UTC, yana-tsylinska requested changes

2021-04-26 09:08 UTC, yana-tsylinska commented on src/app/components/partials/news-list-item/news-list-item.component.scss
> +  font-family: Montserrat;
variables?

2021-04-26 09:08 UTC, yana-tsylinska commented on src/app/components/partials/news-list-item/news-list-item.component.scss
> +  font-family: Montserrat;
перепровір цей файл))

2021-04-26 10:31 UTC, NataliyaKoval commented on src/app/components/partials/news-list-item/news-list-item.component.scss
> +  font-family: Montserrat;
Added variables

2021-04-26 10:31 UTC, NataliyaKoval commented on src/app/components/partials/news-list-item/news-list-item.component.scss
> +  font-family: Montserrat;
Changed

2021-04-26 11:52 UTC, yana-tsylinska approved these changes

2021-04-26 11:53 UTC, merged