Theatre 39 slider
geekhub-php/theatre-front pull request #178
Opened 2021-04-13 15:22 UTC by Kate-Kryvopustova

2021-04-21 16:11 UTC, Serhio77777 approved these changes

2021-05-08 08:28 UTC, yana-tsylinska requested changes

2021-05-08 08:28 UTC, yana-tsylinska commented on src/app/components/home-page/performance-slider/performance-slider.component.scss
> +  font-family: 'Montserrat', serif;
use variables

2021-05-08 08:28 UTC, yana-tsylinska commented on src/app/components/home-page/performance-slider/performance-slider.component.scss
> +  font-style: normal;
remove

2021-05-12 19:09 UTC, yana-tsylinska approved these changes

2021-05-12 20:00 UTC, merged