Theatre 76 repertoire page
geekhub-php/theatre-front pull request #189
Opened 2021-04-22 18:39 UTC by Kate-Kryvopustova

2021-04-23 11:51 UTC, Serhio77777 requested changes

2021-04-23 11:51 UTC, Serhio77777 commented on src/app/components/repertoire/repertoire.component.scss
> +  font-style: normal;
mixins

2021-04-23 11:51 UTC, Serhio77777 commented on src/app/components/repertoire/repertoire.component.scss
> +  height: 500px;
mixins

2021-04-23 11:51 UTC, Serhio77777 commented on src/app/components/repertoire/repertoire.component.ts
> +  p = 1;
What is p?

2021-04-23 11:51 UTC, Serhio77777 commented on src/app/components/repertoire/repertoire-nav-header/repertoire-nav-header.component.html
> +<div class="nav-header-container">
Is that component the same as the Header at the festivals?

2021-04-26 19:57 UTC, yana-tsylinska requested changes

2021-04-26 19:57 UTC, yana-tsylinska commented on src/app/components/repertoire/repertoire-nav-header/repertoire-nav-header.component.scss
> +  font-family: 'Montserrat';
variables

2021-05-03 15:45 UTC, Kate-Kryvopustova commented on src/app/components/repertoire/repertoire.component.scss
> +  height: 500px;
Done

2021-05-03 15:45 UTC, Kate-Kryvopustova commented on src/app/components/repertoire/repertoire.component.scss
> +  font-style: normal;
Done

2021-05-03 15:46 UTC, Kate-Kryvopustova commented on src/app/components/repertoire/repertoire.component.ts
> +  p = 1;
Done

2021-05-03 15:46 UTC, Kate-Kryvopustova commented on src/app/components/repertoire/repertoire-nav-header/repertoire-nav-header.component.scss
> +  font-family: 'Montserrat';
Done

2021-05-08 06:28 UTC, yana-tsylinska approved these changes

2021-05-12 18:55 UTC, merged