Performance
geekhub-php/theatre-front pull request #219
Opened 2021-06-14 15:10 UTC by NataliyaKoval

2021-08-11 17:11 UTC, yana-tsylinska commented on src/app/components/performance/performance.component.scss
> +::ng-deep .ngx-gallery-thumbnail.ngx-gallery-active {
:host ::ng-deep

2021-08-11 17:12 UTC, yana-tsylinska commented on src/app/components/performance/performance.component.scss
> +.details::ng-deep a {
:host

2021-08-11 17:12 UTC, yana-tsylinska approved these changes

2021-08-11 17:12 UTC, yana-tsylinska requested changes
add :host

2021-08-17 07:03 UTC, NataliyaKoval commented on src/app/components/performance/performance.component.scss
> +::ng-deep .ngx-gallery-thumbnail.ngx-gallery-active {
done

2021-08-17 07:04 UTC, NataliyaKoval commented on src/app/components/performance/performance.component.scss
> +.details::ng-deep a {
done

2021-08-18 15:38 UTC, yana-tsylinska approved these changes

2021-08-23 09:54 UTC, merged