Footer was modified
geekhub-php/theatre-front pull request #225
Opened 2021-07-07 16:36 UTC by Tetiana-Dendemarchenko

2021-07-07 17:08 UTC, yana-tsylinska requested changes

2021-07-07 17:08 UTC, yana-tsylinska commented on src/app/components/donate/donate.component.scss
> +    z-index: 100;
??

2021-07-07 17:08 UTC, yana-tsylinska commented on src/app/components/donate/donate.component.ts
> +    window.open(URL, '_blank');
Make it with html

2021-07-07 17:08 UTC, yana-tsylinska commented on src/app/components/home-page/home-page.component.html
> +  </section>-->
Delete unused code

2021-07-07 17:08 UTC, yana-tsylinska commented on src/app/components/home-page/home-page.component.html
> +  <!--<section class="home-page-text__advantages">
Why is it not deleted?

2021-07-07 17:08 UTC, yana-tsylinska commented on src/app/modules/core/components/footer/footer.component.html
> +      <li class="ufc"><span class="ucf-text" i18n="@@createdWithHelp">Site has been created with the help of</span>
ufc? ucf? cuf? fuc?..

2021-07-07 17:08 UTC, yana-tsylinska commented on src/app/modules/core/components/footer/footer.component.html
> +        <div class="copy">
Why is it copy class name?

2021-07-07 17:08 UTC, yana-tsylinska commented on src/app/modules/core/components/header/header.component.scss
> +      right: 306px;
Why 306?

2021-07-07 17:08 UTC, yana-tsylinska commented on src/app/modules/core/components/visually-impaired/visually-impaired.component.html
> +      <img src="assets/images/close 1.svg" class="close-button" alt="Closing button" title="Close"
Same to first error

2021-08-01 09:58 UTC, Tetiana-Dendemarchenko commented
Broke this huge commit into smaller pieces. All the comments (by the team lead) about fixing the code were taken into consideration.

2021-08-01 09:58 UTC, closed without merging